### ISSUE TITLE
Correct dependencies not available

### ISSUE THREAD

**Issue by Jabokoe** [amulware/syzygy#1]
I can find and build a version of Bearded.Utilities, amulware.Graphics and Lidgren.Network projects. Syzygy however won't build because **Bearded.Utilities.SpaceTime** is not present in the beardgame and amulware versions of Bearded.Utilities available on GitHub.

**Comment by paulcscharf** [comment]
That is odd. Can you make sure you have the utilities (from my own repo, not the beardgame one) checked out to the **spacetime2** branch?

I haven't yet gotten around to polishing up that stuff and have it merged into the main branches.

**Comment by Jabokoe** [comment]
Thanks, that works! Also for some reason git modules are suddenly working again for me which would have prevented my mistake in the first place.
